import { User, WorkshopSettings, InventoryItem, Order, Appointment } from './types';

export const DEFAULT_USERS: User[] = [
  {
    id: 'U-ADMIN',
    name: 'Mustafa Al-Zurgany',
    username: 'admin',
    pin: '2026',
    role: 'admin',
    createdAt: '01.01.2026',
    active: true,
    canSettleInvoices: true,
    canDelete: true,
  },
];

export const DEFAULT_WORKSHOP_SETTINGS: WorkshopSettings = {
  workshopName: 'CODE // IT-Werkstatt',
  ownerName: 'Mustafa Al-Zurgany',
  address: '92318 Neumarkt in der Oberpfalz',
  phone: '0176 4174 4443',
  email: 'info@code-ger.com',
  website: 'code-ger.com',
  defaultHourlyRate: 85,
};

export const DEFAULT_INVENTORY: InventoryItem[] = [
  {
    id: 'P-1001',
    name: 'PS5 HDMI-Port (OEM Original)',
    category: 'Konsole',
    qty: 12,
    minQty: 4,
    ek: 7.5,
    supplier: 'Mobilsentrix',
  },
  {
    id: 'P-1002',
    name: 'Thermal Grizzly Conductonaut (Flüssigmetall 1g)',
    category: 'Verbrauchsmaterial',
    qty: 6,
    minQty: 2,
    ek: 6,
    supplier: 'Caseking',
  },
  {
    id: 'P-1003',
    name: 'DualSense Hall-Effect 3D Magnet-Sticks (Paar)',
    category: 'Controller',
    qty: 16,
    minQty: 6,
    ek: 11.5,
    supplier: 'Ginfull',
  },
  {
    id: 'P-1004',
    name: 'SMD Mikrotaster Autoschlüssel (4-Pin)',
    category: 'Autoschlüssel',
    qty: 45,
    minQty: 10,
    ek: 1.2,
    supplier: 'Autel',
  },
  {
    id: 'P-1005',
    name: 'N-Channel MOSFET 30V 40A (Laptop 19V Rail)',
    category: 'Laptop / PC',
    qty: 20,
    minQty: 5,
    ek: 3.2,
    supplier: 'Mouser',
  },
  {
    id: 'P-1006',
    name: 'Amtech NC-559-V2-TF Lötflussmittel (10cc)',
    category: 'Verbrauchsmaterial',
    qty: 5,
    minQty: 2,
    ek: 14.5,
    supplier: 'Amtech Direct',
  },
  {
    id: 'P-1007',
    name: 'PS5 Spender-Mainboard (EDM-010 Donor)',
    category: 'Donor Board (Spender)',
    qty: 2,
    minQty: 1,
    ek: 45,
    supplier: 'Privat',
  },
];

export const INITIAL_DEMO_ORDERS: Order[] = [
  {
    id: 'CODE-9231',
    cust: 'Max Mustermann',
    phone: '0176 4174 4443',
    address: '92318 Neumarkt in der Oberpfalz',
    device: 'PlayStation 5 (Disc Edition)',
    serial: 'AK491823719',
    technician: 'Mustafa Al-Zurgany',
    isB2B: false,
    min: 45,
    rate: 85,
    partEK: 7.5,
    partVKNet: 15,
    consumables: 4.5,
    overhead: 6,
    express: 0,
    netto: 75.63,
    taxRate: 19,
    taxAmount: 14.37,
    brutto: 90.0,
    profit: 63.63,
    date: new Date().toLocaleDateString('de-DE'),
    status: '5. Fertig & Abholbereit',
    paid: 'Bezahlt',
    payMethod: 'Barzahlung',
    faultDescription: 'HDMI-Buchse herausgebrochen, Leiterbahnen beschädigt',
    accessories: 'Nur Konsole ohne Kabel',
  },
  {
    id: 'CODE-4412',
    cust: 'Laura Becker',
    phone: '0151 8912 344',
    address: 'Kornmarkt 4\n92318 Neumarkt',
    device: 'Lenovo ThinkPad T14 Gen 2',
    serial: 'PF29A019B',
    technician: 'Mustafa Al-Zurgany',
    isB2B: false,
    min: 60,
    rate: 85,
    partEK: 14,
    partVKNet: 21,
    consumables: 5.5,
    overhead: 6,
    express: 0,
    netto: 83.19,
    taxRate: 19,
    taxAmount: 15.81,
    brutto: 99.0,
    profit: 63.69,
    date: new Date(Date.now() - 86400000).toLocaleDateString('de-DE'),
    status: '3. Reparatur & Bearbeitung',
    paid: 'Offen',
    payMethod: 'Banküberweisung',
    faultDescription: 'Flüssigkeitsschaden Kaffee, startet nicht mehr',
  },
  {
    id: 'CODE-7708',
    cust: 'Thomas Klein',
    phone: '0170 1209 881',
    address: 'Neumarkter Str. 18\n92364 Deining',
    device: 'DualSense PS5 Controller',
    serial: 'G309184',
    technician: 'Mustafa Al-Zurgany',
    isB2B: false,
    min: 40,
    rate: 85,
    partEK: 11.5,
    partVKNet: 18,
    consumables: 4,
    overhead: 6,
    express: 0,
    netto: 58.82,
    taxRate: 19,
    taxAmount: 11.18,
    brutto: 70.0,
    profit: 43.32,
    date: new Date(Date.now() - 172800000).toLocaleDateString('de-DE'),
    status: '4. Qualitätsprüfung & Test',
    paid: 'Bezahlt',
    payMethod: 'EC-Karte',
    faultDescription: 'Massiver Stick-Drift auf linker Achse (Hall-Effect Umbau)',
  },
  {
    id: 'CODE-1085',
    cust: 'Michael Weber',
    phone: '0160 5543 219',
    address: 'Unterer Markt 8\n92318 Neumarkt',
    device: 'BMW Funkschlüssel (Rautenform)',
    serial: 'BMW-KEY-08',
    technician: 'Mustafa Al-Zurgany',
    isB2B: false,
    min: 30,
    rate: 85,
    partEK: 6.5,
    partVKNet: 12,
    consumables: 3.5,
    overhead: 4,
    express: 0,
    netto: 49.58,
    taxRate: 19,
    taxAmount: 9.42,
    brutto: 59.0,
    profit: 39.58,
    date: new Date().toLocaleDateString('de-DE'),
    status: '1. Eingang & Registrierung',
    paid: 'Offen',
    payMethod: 'Barzahlung',
    faultDescription: 'Akku leer (VL2020), ZV-Taster ohne Funktion',
  },
  {
    id: 'CODE-3042',
    cust: 'Sarah Lindner',
    phone: '0172 9012 441',
    address: 'Hans-Dehn-Str. 5\n92318 Neumarkt',
    device: 'Apple iPhone 14 Pro Max',
    serial: 'DNPRM9012',
    technician: 'Mustafa Al-Zurgany',
    isB2B: false,
    min: 45,
    rate: 85,
    partEK: 0,
    partVKNet: 0,
    consumables: 4,
    overhead: 5,
    express: 0,
    netto: 41.18,
    taxRate: 19,
    taxAmount: 7.82,
    brutto: 49.0,
    profit: 36.18,
    date: new Date().toLocaleDateString('de-DE'),
    status: '2. Labor-Diagnose',
    paid: 'Offen',
    payMethod: 'EC-Karte',
    faultDescription: 'Bootloop nach Speicherüberlauf (Fehler 14)',
  },
];

export const DEFAULT_APPOINTMENTS: Appointment[] = [
  {
    id: 'TERM-101',
    customerName: 'Alexander Weber',
    phone: '0176 8921 345',
    email: 'alex.weber@gmx.de',
    device: 'Sony PlayStation 5 (Disc Edition CFI-1216A)',
    faultDescription: 'HDMI-Port herausgebrochen, Pins verbogen, Leiterbahnen Pad 4 & 7 prüfen. Überhitzungsschutz schaltet sporadisch ab.',
    serviceType: 'HDMI-Port Tausch + Flüssigmetall-Service',
    date: new Date().toISOString().split('T')[0],
    time: '14:30',
    status: 'bestaetigt',
    requiredParts: [
      { partName: 'PS5 HDMI-Port (OEM Original)', inventoryId: 'P-1001', qtyNeeded: 1 },
      { partName: 'Thermal Grizzly Conductonaut (Flüssigmetall 1g)', inventoryId: 'P-1002', qtyNeeded: 1 },
    ],
    estimatedDurationMinutes: 60,
    internalNotes: 'Kunde bringt Konsole persönlich an die Werkbank. Schnellreparatur gewünscht.',
    createdAt: 'Gestern, 18:20',
  },
  {
    id: 'TERM-102',
    customerName: 'Markus Bauer',
    phone: '0151 4455 982',
    email: 'm.bauer@bauernfeind-haustechnik.de',
    device: 'BMW Autoschlüssel (F30 / F10 Komfortzugang)',
    faultDescription: 'Zentralverriegelung öffnet nur aus nächster Nähe. Akku lädt im Zündschloss nicht mehr auf. Taster "Kofferraum" hat keinen Druckpunkt.',
    serviceType: 'Schlüssel-Platinenreparatur',
    date: new Date().toISOString().split('T')[0],
    time: '16:00',
    status: 'bestaetigt',
    requiredParts: [
      { partName: 'SMD Mikrotaster Autoschlüssel (4-Pin)', inventoryId: 'P-1004', qtyNeeded: 2 },
      { partName: 'Panasonic VL2020 Akku 90° Beine', inventoryId: undefined, qtyNeeded: 1 },
    ],
    estimatedDurationMinutes: 30,
    internalNotes: 'Transponder-Spule 125kHz auf Platinenbruch prüfen.',
    createdAt: 'Heute, 08:45',
  },
  {
    id: 'TERM-103',
    customerName: 'Florian Eder',
    phone: '0170 3391 822',
    email: 'florian.eder@architekten-eder.de',
    device: 'Apple MacBook Pro 16" (A2141 Logic-Board)',
    faultDescription: 'Gerät reagiert nicht auf Ladegerät (0.00A Stromaufnahme auf 5V USB-C). Verdacht auf Kurzschluss auf PPBUS_G3H oder defekten CD3217 Lade-Controller.',
    serviceType: 'Logic-Board Mikrolöten & Kurzschlussbeseitigung',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    time: '11:00',
    status: 'bestaetigt',
    requiredParts: [
      { partName: 'N-Channel MOSFET 30V 40A (Laptop 19V Rail)', inventoryId: 'P-1005', qtyNeeded: 1 },
      { partName: 'CD3217B12 USB-C Controller IC', inventoryId: undefined, qtyNeeded: 1 },
    ],
    estimatedDurationMinutes: 90,
    internalNotes: 'Thermal-Kamera-Scan zur Lokalisierung des Kurzschlusses vorbereiten.',
    createdAt: 'Vorgestern, 14:10',
  },
  {
    id: 'TERM-104',
    customerName: 'Daniel Schmidt',
    phone: '0160 7712 904',
    device: 'Sony DualSense PS5 Wireless Controller',
    faultDescription: 'Extremer Stick-Drift auf linkem Analogstick (Charakter läuft selbstständig nach vorne). Kunde wünscht langlebiges Hall-Effect Magnet-Upgrade.',
    serviceType: 'Hall-Effect Stick Upgrade & Kalibrierung',
    date: new Date(Date.now() + 86400000).toISOString().split('T')[0],
    time: '15:30',
    status: 'bestaetigt',
    requiredParts: [
      { partName: 'DualSense Hall-Effect 3D Magnet-Sticks (Paar)', inventoryId: 'P-1003', qtyNeeded: 1 },
    ],
    estimatedDurationMinutes: 45,
    internalNotes: 'Nach Einbau über Hardware-Tester Mittelpunkt kalibrieren.',
    createdAt: 'Heute, 09:15',
  },
  {
    id: 'TERM-105',
    customerName: 'Tobias Lang',
    phone: '0171 6620 119',
    device: 'Nintendo Switch OLED',
    faultDescription: 'Gerät lädt nicht mehr, USB-C Buchse innen verbogen, Konsole schaltet nicht ein. Möglicherweise M92T36 IC durch Überspannung zerstört.',
    serviceType: 'USB-C Buchsentausch & Power Management Reparatur',
    date: new Date(Date.now() + 86400000 * 2).toISOString().split('T')[0],
    time: '14:00',
    status: 'teile_fehlen',
    requiredParts: [
      { partName: 'Nintendo Switch Type-C Buchse 12-Pin', inventoryId: undefined, qtyNeeded: 1 },
      { partName: 'M92T36 Power Management IC', inventoryId: undefined, qtyNeeded: 1 },
    ],
    estimatedDurationMinutes: 75,
    internalNotes: 'Achtung: M92T36 IC aktuell nicht im Lager vorrätig! Muss beim Lieferanten bestellt werden.',
    createdAt: 'Heute, 10:30',
  },
];
